# Generated by Django 4.0.6 on 2022-07-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mdesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('ket', models.TextField(null=True)),
            ],
            options={
                'db_table': 'desa',
            },
        ),
        migrations.CreateModel(
            name='Mjabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('ket', models.TextField(null=True)),
            ],
            options={
                'db_table': 'jabatan',
            },
        ),
        migrations.CreateModel(
            name='Mkabupaten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('ket', models.TextField(null=True)),
            ],
            options={
                'db_table': 'kabupaten',
            },
        ),
        migrations.CreateModel(
            name='Mkecamatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('ket', models.TextField(null=True)),
            ],
            options={
                'db_table': 'kecamatan',
            },
        ),
        migrations.CreateModel(
            name='Mpendidikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('ket', models.TextField(null=True)),
            ],
            options={
                'db_table': 'pendidikan',
            },
        ),
    ]
