# Generated by Django 4.0.6 on 2022-07-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdesa',
            name='ket',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mjabatan',
            name='ket',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mkabupaten',
            name='ket',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mkecamatan',
            name='ket',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mpendidikan',
            name='ket',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
