# Generated by Django 4.0.6 on 2022-07-16 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0002_alter_mdesa_ket_alter_mjabatan_ket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mguru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.IntegerField()),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=200)),
                ('tgl_lahir', models.DateField()),
                ('jenis_kelamin', models.CharField(choices=[('laki-laki', 'laki-laki'), ('perempuan', 'perempuan')], max_length=100, null=True)),
                ('desa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='absensi.mdesa')),
                ('jabatan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='absensi.mjabatan')),
                ('kabupaten', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='absensi.mkabupaten')),
                ('kecamatan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='absensi.mkecamatan')),
                ('pendidikan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='absensi.mpendidikan')),
            ],
            options={
                'db_table': 'guru',
            },
        ),
    ]
