# Generated by Django 4.0.6 on 2022-07-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0005_mabsen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mabsen',
            name='jam_masuk',
            field=models.DateTimeField(null=True),
        ),
    ]
