# Generated by Django 4.0.6 on 2022-07-16 19:16

from django.db import migrations, models
import tomlkit.api


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0007_alter_mabsen_jam_masuk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mabsen',
            name='jam_masuk',
            field=models.DateTimeField(default=tomlkit.api.datetime),
        ),
    ]
